### PR TITLE
Fixed the empty view option

### PR DESCRIPTION
**Pull request by mohitkumawat310**
The view option was visible even if zero columns were hideable. Please mark it as hactoberfest entry if you are going to merge this.

### CODE REVIEW

**Comment by sadmann7** [comment]
Thanks.

Where can i mark it as as hacktoborfest?

**Comment by mohitkumawat310** [comment]
> Thanks.
> 
> Where can i mark it as as hacktoborfest?

In merge title. 
Also thanks for this amazing code I learnt alot from this. Made an advance version of this woth more features in an admin panel which will i open source soon. And also push the changes here.

**Comment by mohitkumawat310** [comment]
> Thanks.
> 
> Where can i mark it as as hacktoborfest?

"Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR/MR."

Add this in label

**Comment by sadmann7** [comment]
Sorry for the long delay.

I added the topics hactoberfest. I can just merge it now right? And it will be considered in the hacktoberfest stuffs

**Comment by sadmann7** [comment]
Sorry totally forgot about it.

Thanks a lot

**Pull request merged**
